TimeSheetApp/Models/TableViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace TimeSheetApp.Models
{
    public class TableViewModel
    {
       public Models.Sheet Sheet {get; set;}
       public string Holiday { get; set; }
       public string Approved { get; set; }
    }
}

TimeSheetApp/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace TimeSheetApp.Controllers
{
    public class TableController : Controller
    {

        //
        // GET: /Table/
        private db8bc58a7c5b7347cbb656a21900e60022Entities db = new db8bc58a7c5b7347cbb656a21900e60022Entities();
        private int currentSheet = -1;
        public ActionResult Index(int id = 0)
        {

            var email = User.Identity.Name.Split('-')[0];
            if (email == null || id == 0)
                return RedirectToAction("Index", "Home");
            ViewBag.SheetID = id;
            //        currentSheet = id;
            Session["SheetID"] = id;
            currentSheet = id;
            Models.Sheet sheet = SingleSheet(id);

            if (sheet.Email != User.Identity.Name.Split('-')[0] && User.Identity.Name.Split('-')[1] == (false).ToString())
                return RedirectToAction("Index", "Home");

            if (sheet == null)
                return RedirectToAction("Index", "Home");
            string holiday = WeekHolidays(sheet.StartDate);

            TimeSheetApp.Models.TableViewModel table = new TimeSheetApp.Models.TableViewModel
            {
                Sheet = sheet,
                Holiday = holiday,
                Approved = sheet.ApprovedDays
            };
            return View(table);
        }

        [HttpGet]
        public ActionResult DayChange(int sheetID, int day = -1)
        {
            if (day == -1)
                return RedirectToAction("Index", "Home");
            ViewData.Add("SheetId", sheetID);
            HttpCookie UserInfo = Request.Cookies["UserInfo"];
            UserInfo["TargetSheet"] = sheetID.ToString();
            Response.Cookies.Add(UserInfo);
            var Days =
                        from T in db.Tasks
                        where T.SheetId == sheetID
                        select new TimeSheetApp.Models.DayViewModel
                        {
                            dayTask = new TimeSheetApp.Models.Task
           {

               Description = T.TaskDescription,
               HoursDone = T.HoursWorked,
               Notes = T.TaskNotes,
               SheetId = T.SheetId,
               TaskId = T.TaskId
           }
            ,
                            hourValue = 0
                        };

            List<TimeSheetApp.Models.DayViewModel> list = new List<TimeSheetApp.Models.DayViewModel>();
            foreach (TimeSheetApp.Models.DayViewModel D in Days)
                list.Add(new TimeSheetApp.Models.DayViewModel { dayTask = D.dayTask, hourValue = (int)(D.dayTask.HoursDone[0] - '0') });

            TimeSheetApp.Models.DayViewModelList ret = new TimeSheetApp.Models.DayViewModelList();
            ret.DayTasks = list;
            ret.day = day;
            return View(ret);
        }

        [HttpPost]
        public ActionResult DayChange(TimeSheetApp.Models.DayViewModelList Days)
        {

            int id = int.Parse(Request.Cookies["UserInfo"]["TargetSheet"].ToString());
            int day = Days.day;
            int sheetId = id;
            List<char> tasks = new List<char>();
            if (ModelState.IsValid)
            {
                foreach (Models.DayViewModel D in Days.DayTasks)
                {
                    tasks.Add((char)(D.hourValue + '0'));

                }


                var taskList = from T in db.Tasks
                               where T.SheetId == sheetId
                               select T;
                int count = 0;
                foreach (var T in taskList)
                {
                    T.HoursWorked = ReplaceAtIndex(day, tasks[count], T.HoursWorked);
                    db.Entry(T).State = System.Data.EntityState.Modified;
                    count++;
                }
                db.SaveChanges();

                return RedirectToAction("Index", "Table", new { id = sheetId });
            }
            return View();
        }

        [HttpGet]
        public ActionResult Approve(int day = -1, int approve = -1)
        {

            int sheetId = int.Parse(Session["SheetID"].ToString());
            if (day == -1 || approve == -1)
                return RedirectToAction("Index", "Table", new { id = sheetId });
            char choice = '1';
            if (approve == 0)
                choice = '2';

            var EditedSheet = db.Sheets.Find(sheetId);
            string App = EditedSheet.ApprovedDays;
            EditedSheet.ApprovedDays = ReplaceAtIndex(day, choice, App);
            db.Entry(EditedSheet).State = System.Data.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", "Table", new { id = sheetId });
        }

        private Models.Sheet SingleSheet(int id)
        {
            IEnumerable<TimeSheetApp.Models.Sheet> sheets = from sheet in db.Sheets
                                                            join user in db.SystemUsers
                                                            on sheet.Email equals user.Email
                                                            where sheet.SheetId == id
                                                            select new Models.Sheet
                                                            {
                                                                SheetId = sheet.SheetId,
                                                                StartDate = sheet.DateStarted,
                                                                Email = sheet.Email,
                                                                ApprovedDays = sheet.ApprovedDays,

                                                                UserModel = new Models.UserModel
                                                                {
                                                                    FirstName = user.FirstName,
                                                                    LastLogin = user.LastLogin,
                                                                    LastName = user.LastName,
                                                                    Mobile = user.Mobile,
                                                                    Email = user.Email,
                                                                    Admin = user.Admin
                                                                },
                                                                Task =
                                                             (from task in db.Tasks
                                                              //join task in db.Tasks
                                                              //on sheet.SheetId equals task.SheetId
                                                              where task.SheetId == id
                                                              select new Models.Task
                                                              {
                                                                  TaskId = task.TaskId,
                                                                  Description = task.TaskDescription,
                                                                  Notes = task.TaskNotes,
                                                                  SheetId = task.SheetId,
                                                                  HoursDone = task.HoursWorked
                                                              }
                                                                )
                                                            };
            Models.Sheet singleSheet = null;
            foreach (Models.Sheet s in sheets)
            {
                singleSheet = s;
                break;
            }

            return singleSheet;

        }

        private string WeekHolidays(DateTime start)
        {
            string holiday = "0000011";
            DateTime current = start;

            for (int i = 0; i < 7; i++)
            {
                var email = User.Identity.Name.Split('-')[0];
                var query = from scheduledholiday in db.ScheduledHolidays
                            //where scheduledholiday.UserEmail==email && scheduledholiday.HolidayDay.Day == current.Day && scheduledholiday.HolidayDay.Month == current.Month
                            select scheduledholiday;
                bool isHoliday = false;
                foreach (var SH in query)
                {
                    if (InRange(SH.HolidayStart, SH.HolidayEnd, current))
                    {
                        isHoliday = true;
                        break;
                    }
                }

                if (isHoliday)
                    holiday = ReplaceAtIndex(i, '1', holiday);

                if (holiday[i] == '0')
                {

                    var casual = from casualholiday in db.CasualHolidays
                                 where casualholiday.UserEmail == email && casualholiday.HolidayDay.Day == current.Day && casualholiday.HolidayDay.Month == current.Month && casualholiday.HolidayDay.Year == current.Year
                                 select casualholiday;
                    if (casual != null && casual.Count() != 0)
                        holiday = ReplaceAtIndex(i, '1', holiday);
                }
                current = current.AddDays(1);
            }
            return holiday;
        }
        private string ReplaceAtIndex(int i, char value, string word)
        {
            char[] letters = word.ToCharArray();
            letters[i] = value;
            return string.Join("", letters);
        }

        private bool InRange(DateTime start, DateTime end, DateTime day)
        {
            start = start.AddHours(-start.Hour);
            start = start.AddMinutes(-start.Minute + 1);

TimeSheetApp/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;

namespace TimeSheetApp.Controllers
{
    public class TaskController : Controller
    {
        //
        // GET: /Task/
        private db8bc58a7c5b7347cbb656a21900e60022Entities db = new db8bc58a7c5b7347cbb656a21900e60022Entities();

        public ActionResult Index()
        {
            if (!Request.IsAuthenticated || Request.Cookies["UserInfo"] == null) return View();
            var email = User.Identity.Name.Split('-')[0];

            //LINQ Query to get All Tasks
            IEnumerable<TimeSheetApp.Models.Task> query =
                            from task in db.Tasks
                            join sheet in db.Sheets
                            on task.SheetId equals sheet.SheetId
                            where sheet.Email == email
                            select new TimeSheetApp.Models.Task
                            {
                                TaskId = task.TaskId , 
                                Description = task.TaskDescription ,
                                Notes = task.TaskNotes , 
                                HoursDone = task.HoursWorked ,
                                SheetId = task.SheetId,
                                Sheet = new Models.Sheet
                                {
                                    SheetId = sheet.SheetId , 
                                    Email = sheet.Email ,
                                    ApprovedDays = sheet.ApprovedDays ,
                                    StartDate = sheet.DateStarted 
                                }
                            };

            return View(query);
        }
        public ActionResult Delete(int ID = 0)
        {
            if (ID == 0) return Redirect(Request.UrlReferrer.ToString());
            var T =db.Tasks.Find(ID);
            if (T == null) return Redirect(Request.UrlReferrer.ToString());
            int sheetID = T.SheetId;
            deleteTask(ID);
            db.SaveChanges();
            return RedirectToAction("Index", "Table", new { id = sheetID });
        }
        public void deleteTask(int ID)
        {
            var task = db.Tasks.Find(ID);
            if (task == null) return;
            db.Entry(task).State = System.Data.EntityState.Deleted;
            db.SaveChanges();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(TimeSheetApp.Models.Task Task)
        {
            if (ModelState.IsValid)
            {
                var task = db.Tasks.Create();
                //task.SheetId = ID;
                task.SheetId = int.Parse(Request.Cookies["UserInfo"]["TargetSheet"].ToString());
                task.HoursWorked = "0000000";
                task.TaskDescription = Task.Description;
                task.TaskNotes = Task.Notes;
                db.Tasks.Add(task);
                db.SaveChanges();

                return RedirectToAction("Index", "Table", new { id=task.SheetId });
            }

            return View();
        }
        public ActionResult Details(int id =0)
        {
            var T = db.Tasks.Find(id);
            if(T == null)
            return HttpNotFound();
            TimeSheetApp.Models.Task ret = new TimeSheetApp.Models.Task
            {
                TaskId = T.TaskId,
                Description = T.TaskDescription,
                Notes = T.TaskDescription,
                SheetId = T.SheetId,
                HoursDone = T.HoursWorked
            };
            return View(ret);
        }

    }
}

TimeSheetApp/Views/Table/DayChange.cshtml
@model TimeSheetApp.Models.DayViewModelList

@{
    ViewBag.Title = "DayChange";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset  style="text-align:center">
        <legend>Hours Done</legend>
        @for (int i = 0; i < Model.DayTasks.Count; i++)
        {
            
            <div>
                <div>Task @(i+1) : @Html.DisplayFor(m => m.DayTasks[i].dayTask.Description)</div>
                <div>Notes : @Html.DisplayFor(m => m.DayTasks[i].dayTask.Notes)</div>
                <div>@Html.EditorFor(m => m.DayTasks[i].hourValue)</div>
                <hr />
            </div>
        }
        <p>
            <input type="submit" value="Change" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TimeSheetApp/Views/Table/Index.cshtml
@model TimeSheetApp.Models.TableViewModel

@{
    ViewBag.Title = "TimeSheet - " + Model.Sheet.StartDate.ToString("ddd dd MMM yyyy") + " " + Model.Sheet.StartDate.AddDays(6).ToString("ddd dd MMM yyyy");
   Response.Cookies["UserInfo"]["TargetSheet"] = Model.Sheet.SheetId.ToString();
    string OnClick = "";
}

@functions
{
    
    int getHour(char c)
    {
        if (c == '0') return 0;
        else return (int)(c - '0');
    }

    int totalHours(TimeSheetApp.Models.Task task)
    {
        int sum = 0;
        for (int i = 0; i < 7; i++)
            if (Model.Holiday[i] == '0')
                sum += (int)(task.HoursDone[i] - '0');
        return sum;
    }

    int totalDayHours(int day)
    {
        if (Model.Holiday[day] == '1')
            return 0;
        int sum = 0;
        foreach (var task in Model.Sheet.Task)
            sum += (int)(task.HoursDone[day] - '0');
        return sum;
    }
    int totalSum()
    {
        int sum = 0;
        for (int i = 0; i < 7; i++)
            if (Model.Holiday[i] == '0')
                foreach (var task in Model.Sheet.Task)
                    sum += (int)(task.HoursDone[i] - '0');
        return sum;
    }
}

<h2 style="text-align: center">Timesheet:  @Model.Sheet.StartDate.ToString(" ddd dd MMM yyyy ") - @Model.Sheet.StartDate.AddDays(6).ToString(" ddd dd MMM yyyy")</h2>
<h3 style="text-align: center">Owner : @Model.Sheet.UserModel.FirstName <span></span> @Model.Sheet.UserModel.LastName</h3>


<div id="SheetsTable">
    <div id ="CreateTask" style="text-align:center;font-family:Verdana;font:600;font-size:large">
    @Html.ActionLink("New Task", "Create", "Task")
        </div>
    <table id="one-column-emphasis" summary="My Timesheets" style="width: 100%; text-align: center">
        <colgroup>
            <col class="oce-first" />
        </colgroup>
        <thead>
            <tr>
                <th style="width: 15%">Date </th>
                <th></th>
                @foreach (var task in Model.Sheet.Task)
                {                      
                    <th 
                    onclick="location.href='../../Task/Details/@task.TaskId';">@task.Description
                    </th>                            
                }
                <th style="background-color: darkmagenta; color: white; width: 10%">Total Hours </th>
                <th style="background-color: #037dff; color: white; width: 7%">Approved</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @for (int i = 0; i < 7; i++)
            {

                if (Model.Holiday[i] == '0')
                { OnClick = "location.href='../DayChange?SheetID=" + Model.Sheet.SheetId + "&day=" + i + "'"; }
                else
                { OnClick = ""; }
                
                <tr onclick="@OnClick">

                    @if (Model.Sheet.StartDate.AddDays(i).Day == DateTime.Now.Day && Model.Sheet.StartDate.AddDays(i).Month == DateTime.Now.Month && Model.Sheet.StartDate.AddDays(i).Year == DateTime.Now.Year)
                    {
                        <td style="color: #fff; background-color: #037dff"><strong>@Model.Sheet.StartDate.AddDays(i).ToString("ddd dd MMM yyyy")</strong></td>
                    }
                    else if (Model.Holiday[i] == '1')
                    {
                        <td style="background-color: #dddcdc">@Model.Sheet.StartDate.AddDays(i).ToString("ddd dd MMM yyyy")</td>
                    }
                    else
                    {
                        <td>@Model.Sheet.StartDate.AddDays(i).ToString("ddd dd MMM yyyy")</td>
                    }
                    <td></td>
                    @foreach (var task in Model.Sheet.Task)
                    {
                        if (Model.Holiday[i] == '0')
                        {
                            if (Model.Approved[i] == 1)
                            {
                        <td style="background-color: #b6ff00"><strong>@getHour(task.HoursDone[i]) </strong></td>
                            }
                            else if (Model.Approved[i] == 2)
                            {
                        <td style="background-color: #fb4444"><strong>@getHour(task.HoursDone[i]) </strong></td>
                            }
                            else
                            {
                        <td><strong>@getHour(task.HoursDone[i]) </strong></td>
                            }
                        }
                        else // Day is Holiday
                        {
                        <td><strong style="color: gray">- </strong></td>                        
                        }
                    }
                    <td style="background-color: wheat; color: black">
                        @totalDayHours(i)
                    </td>

                    @if (Model.Approved[i] == '0')
                    {
                        <td>
                            @if (User.Identity.Name.Split('-')[1] == (true).ToString())
                            {
                                @Html.ActionLink("Approve|", "Approve", new { day = i, approve = 1 })
                                
                                @Html.ActionLink("Reject", "Approve", new { day = i, approve = 0 })
                            }
                        </td>
                    }
                    else if (Model.Approved[i] == '1')
                    {
                        <td style="background-color:#31ff00">
                            @if (User.Identity.Name.Split('-')[1] == (true).ToString())
                            {
                                @Html.ActionLink("Reject", "Approve", new { day = i, approve = 0 })
                            }
                        </td>
                    }
                    else if (Model.Approved[i] == '2')
                    {
                        <td style="background-color:#f00">
                            @if (User.Identity.Name.Split('-')[1] == (true).ToString())
                            {
                                @Html.ActionLink("Approve", "Approve", new { day = i, approve = 1 })
                            }
                        </td>
                    }
                </tr>
            }
            <tr>
                <td><strong>Hours Worked on Task </strong></td>
                <td style="background-color: wheat; color: black"></td>
                @foreach (var task in Model.Sheet.Task)
                { 
                    <td style="background-color: wheat; color: black">@totalHours(task)</td>
                }
                <td style="background-color: darkmagenta; color: white"><strong>@totalSum()</strong></td>
                <td></td>
            </tr>
        </tbody>
    </table>
 
</div>